name: 10x Ubuntu VPS
on:
  workflow_dispatch:

jobs:
  vps:
    runs-on: ubuntu-latest
    timeout-minutes: 360      # mỗi VPS tối đa ~6 giờ
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        idx: [1,2,3,4,5,6,7,8,9,10]   # 10 VPS song song
    steps:
      - name: Start SSH session (tmate) - VPS #${{ matrix.idx }}
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false  # KHÔNG yêu cầu SSH key; có link là vào được
